routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', 'PageController@home');

Auth::routes();

Route::get('profile/view/{username?}', 'ProfileController@index');
Route::post('profile/search', 'ProfileController@search');

Route::post('modal/create', 'ModalController@create');

Route::group(['middleware' => ['auth']], function () {

    // Profile Routes
    Route::group(['prefix' => 'profile'], function () {
        Route::get('/', 'ProfileController@index');
        Route::get('edit', 'ProfileController@edit');
        Route::post('store', 'ProfileController@store');
        Route::post('upgrade', 'ProfileController@upgrade');
        Route::post('degrade', 'ProfileController@degrade');
    });

    // Workout Routes
    Route::get('workouts', 'WorkoutController@index');
    Route::get('workouts/fixusers', 'WorkoutController@fixUsers');
    Route::group(['prefix' => 'workout'], function () {
        Route::get('item/{id?}', 'WorkoutController@item');
        Route::get('view/{id}', 'WorkoutController@view');
        Route::post('store', 'WorkoutController@store');

        Route::group(['prefix' => 'step'], function () {
            Route::post('store', 'WorkoutStepController@store');
            Route::post('remove', 'WorkoutStepController@remove');
            Route::post('sort', 'WorkoutStepController@sort');
        });

        Route::group(['prefix' => 'user'], function () {
            Route::post('add', 'WorkoutController@userAdd');
            Route::post('remove', 'WorkoutController@userRemove');
            Route::post('leave', 'WorkoutController@userLeave');
        });

        Route::post('group/add', 'WorkoutController@groupAdd');
        Route::post('group/remove', 'WorkoutController@groupRemove');
    });

    // Group Routes
    Route::get('groups', 'GroupController@index');
    Route::group(['prefix' => 'group'], function () {
        Route::get('item/{id?}', 'GroupController@item');
        Route::get('view/{id}', 'GroupController@view');
        Route::post('store', 'GroupController@store');

        Route::group(['prefix' => 'user'], function () {
            Route::post('add', 'GroupController@userAdd');
            Route::post('promote', 'GroupController@userPromote');
            Route::post('demote', 'GroupController@userDemote');
            Route::post('remove', 'GroupController@userRemove');
            Route::post('leave', 'GroupController@userLeave');
        });
    });

    Route::post('device/remove', 'DeviceController@remove');

});

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Group extends Model
{
    public function users()
    {
        return $this->belongsToMany('App\User', 'group_user', 'group_id', 'user_id')->withPivot('access');
    }

    public function workouts()
    {
        return $this->belongsToMany('App\Workout', 'workout_group', 'group_id', 'workout_id');
    }

    public function image()
    {
        return $this->hasOne('App\Media', 'item_id', 'id')->where('item_type', 'group');
    }

    public function getImagePathAttribute($value)
    {
        if ($this->image) {
            return asset('storage/'.$this->image->path);
        }
        return asset('img/avatar.png');
    }

    public function getUrlAttribute()
    {
        return url('group/item/' . $this->id);
    }

    public function getViewUrlAttribute()
    {
        return url('group/view/' . $this->id);
    }

    public function getOwnerListAttribute()
    {
        return $this->users()->wherePivot('access', 9)->pluck('user_id')->toArray();
    }

    public function getMemberListAttribute()
    {
        return $this->users()->pluck('user_id')->toArray();
    }

    public function isMember($user_id = null)
    {
        if (!$user_id) {
            $user_id = Auth::user()->id;
        }
        return (in_array($user_id, $this->member_list));
    }

    public function isOwner($user_id = null)
    {
        if (!$user_id) {
            $user_id = Auth::user()->id;
        }
        if ($this->isCoach($user_id)){
            return true;
        }
        return in_array($user_id, $this->owner_list);
    }

    public function isCoach($user_id = null)
    {
        if (!$user_id) {
            $user_id = Auth::user()->id;
        }
        $user = User::find($user_id);
        return ($user && $this->isMember($user_id) && $user->role_id == 2);
    }

    public function getTotalMembersAttribute()
    {
        return $this->users->count();
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Group;
use App\Media;
use App\Helpers\R;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class GroupController extends Controller
{
    private $group;

    public function index(Request $request)
    {
        $user = Auth::user();
        return view('group.index')->withUser($user)->withTitle(__('Groups'));
    }

    private function validateGroup(Request $request)
    {
        $r = new R(false);
        $item = Group::find($request->group_id);

        if ($item) {
            if (!$item->isOwner()) {
                $r->message = __('Access Denied');
                return $r;
            }
        } else {
            $r->message = __('Group Not Found');
            return $r;
        }
        $this->group = $item;
        $r->status = true;
        return $r;
    }

    public function userPromote(Request $request)
    {
        $r = $this->validateGroup($request);
        if ($r->status == false) {
            return response()->json($r);
        }

        $user = User::find($request->user_id);
        if (!$user) {
            return response()->json(new R(false, __('User Not Found')));
        }

        $this->group->users()->updateExistingPivot($request->user_id, ['access' => 9]);

        $view = view('modules.user.item')->withUser($user)->withItem($this->group)->render();
        return response()->json(new R(true, __('User Promoted to Owner'), $view));
    }

    public function userDemote(Request $request)
    {
        $r = $this->validateGroup($request);
        if ($r->status == false) {
            return response()->json($r);
        }

        $user = User::find($request->user_id);
        if (!$user) {
            return response()->json(new R(false, __('User Not Found')));
        }

        $this->group->users()->updateExistingPivot($request->user_id, ['access' => 1]);

        $view = view('modules.user.item')->withUser($user)->withItem($this->group)->render();
        return response()->json(new R(true, __('User Demoted to Member'), $view));
    }

    public function userRemove(Request $request)
    {

        $r = $this->validateGroup($request);
        if ($r->status == false) {
            return response()->json($r);
        }

        $user = User::find($request->user_id);
        if (!$user) {
            return response()->json(new R(false, __('User Not Found')));
        }
        $this->group->users()->detach($request->user_id);

        return response()->json(new R(true, __('User Removed from Group')));
    }

    public function userLeave(Request $request)
    {
        $group = Group::find($request->group_id);
        if(!$group){
            response()->json(new R(false, __('Group Not Found')));
        }

        $user = Auth::user();
        $group->users()->detach($user->id);

        return response()->json(new R(true, __('Leaving Group')));
    }

    public function userAdd(Request $request)
    {
        if (!$request->users) {
            return response()->json(new R(false, __('Select Users To Add')));
        }

        $r = $this->validateGroup($request);
        if ($r->status == false) {
            return response()->json($r);
        }

        $user_ids = $request->users;
        foreach ($user_ids as $user_id) {
            $user = User::find($user_id);
            if ($user) {
                $this->group->users()->syncWithoutDetaching([$user->id => ['access' => 1]]);
            }
        }

        return response()->json(new R(true, __('Users Added')));
    }

    public function item($id = null)
    {
        $item = null;
        $title = __('Create Group');
        if ($id) {
            $title = __('Edit Group');
            $item = Group::find($id);
            if(!$item->isOwner(Auth::user()->id)){
                return abort(403);
            }
        }
        return view('group.item')->withItem($item)->withTitle($title);
    }

    public function view($id = null)
    {
        $title = __('View Group');
        $item = Group::find($id);
        if(!$item){
            return abort(404);
        }
        return view('group.item')->withItem($item)->withTitle($title)->withReadonly(true);
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);

        $r = new R;
        $r->message = __('Group Created');
        $user = Auth::user();
        $item = Group::find($request->id);

        if ($item) {
            if (!$item->isOwner()) {
                return response()->json(new R(false, __('Access Denied')));
            }
            $r->message = __('Group Updated');
        } else {
            $item = new Group;
        }
        $item->name = $request->name;
        $item->description = $request->description;
        $item->save();

        if ($request->has('image')) {
            $media = Media::createOrUpdate($request, 'image', $item->id, 'group');
        }
        $item->users()->syncWithoutDetaching([$user->id => ['access' => 9]]);
        $r->status = true;
        $r->url = $item->url;
        return $r->toArray();

    }
}

resources/views/group/index.blade.php
@extends('layouts.app')

@section('sidebar')
@include('group.sidebar')
@endsection

@section('content')
<h1>{{$title}}</h1>
@if ($user->groups->count() > 0)
<div class="card-columns">
    @foreach ($user->groups as $item)
    <div class="card">

        @if ($item->image_path)
        <a href="{{ $item->view_url }}">
            <img class="card-img-top" src="{{ $item->image_path }}" alt="{{ $item->name }}">
        </a>
        @endif

        <div class="card-body">
            <a href="{{ $item->view_url }}">
                <h5 class="card-title">
                    {{ $item->name }}
                </h5>
            </a>
            @if ($item->total_duration)
            <h6 class="card-subtitle">
                {{ __('Total Members') }}: {{ $item->total_members }} {{ __('minute(s)') }} <br>
                {{ __('Group Leader') }}: {{ $item->leader }} {{ __('minute(s)') }} <br>
                {{ __('Workouts') }}: {{ $item->total_workouts }} {{ __('step(s)') }} <br>
                {{ __('Created At') }}: {{$item->created_at->toFormattedDateString()}} <br>
                {{ __('Updated At') }}: {{$item->updated_at->toFormattedDateString()}} <br>
            </h6>
            @endif
            @if ($item->description)
            <p class="card-text">
                {{ $item->description }}
            </p>
            @endif
        </div>
        <div class="card-footer clearfix">
            @if ($item->isOwner())
            <a href="{{ $item->url }}" class="card-link float-right btn btn-primary">{{__('Edit')}}</a>
            @endif
        </div>

    </div>
    @endforeach
</div>
@else
<div class="alert alert-info">
    {{__('Create your first group using button above')}}
</div>
@endif
@endsection

resources/views/group/item.blade.php
@extends('layouts.app')

@section('sidebar')
    @include('group.sidebar')
@endsection

@section('content')
<h1>{{$title}}</h1>
<div class="row justify-content-center">
    <div class="col-md-8">
        <form action="">
            @if (isset($item))
                <input type="hidden" name="id" value="{{ $item->id }}">
                <input type="hidden" name="group_id" value="{{ $item->id }}">

                <h4>{{__("Shared Workouts")}}</h4>
                @forelse ($item->workouts as $workout)
                    <a href="{{ $workout->view_url }}" target="_blank" class="user_avatar" title="{{ $workout->name }}">
                        <img src="{{ $workout->image_path }}" alt="{{ $workout->name }}" class="">
                    </a>
                @empty
                    <div class="alert alert-info">
                        {{__("Nobody shared any workout to group")}}
                    </div>
                @endforelse
            @endif
            @include('modules.form.field',[
                'name'=>'image',
                'label'=>'Image',
                'type'=>'image',
                'col'=>true,
            ])
            @include('modules.form.field',[
                'name'=>'name',
                'label'=>'Name',
                'col'=>true,
            ])
            @include('modules.form.field',[
                'name'=>'description',
                'label'=>'Description',
                'type'=>'textarea',
                'col'=>true,
            ])
            @if (isset($item))
                @if (!isset($readonly))
                    @php
                        $modal = new App\Helpers\Modal('groupUserAdd',__('Add User'),'group.modal.user.add',['group_id'=>$item->id]);
                    @endphp
                    <div class="text-center mb-3">
                        <a href="#" data-action="modalCreate" data-modal="{{ $modal->toJson() }}" class="btn btn-primary">{{ __('Add User') }}</a>
                    </div>
                @endif
                <div class="group-users-container">
                    @include('modules.user.list',['users'=>$item->users])
                </div>
            @endif
            @if (!isset($readonly))
                <div class="text-center">
                    @include('modules.response')
                    <a href="#" class="btn btn-primary" data-action="groupStore">{{ (isset($item))?__('Update'):__('Save') }}</a>
                </div>
            @endif
        </form>
    </div>
</div>
@endsection

resources/views/group/sidebar.blade.php
<a href="{{ url('group/edit') }}" class="list-group-item list-group-item-action bg-light">{{__('Create Group')}}</a>

resources/views/group/users.blade.php
@dump($item->users)
@foreach ($item->user as $user)
    @include('modules.user.list.item')
@endforeach